project        = "<host project name>"
compute_region = "<gcp region>"
data_region    = "<gcp region including multi-regions eu|us>"
bq_landing_dataset_name = "<BigQuery landing dataset>"
bq_curated_dataset_name = "<BigQuery curated dataset>"
bq_consumption_dataset_name = "<BigQuery consumption dataset>"
terraform_service_account = "bq-backup-mgr-terraform@<host project name>.iam.gserviceaccount.com"
